services:

  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: flask_movie:2.0.2
    container_name: movie_api
    command: python wsgi.py
    ports:
      - 5005:5000
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/flask_movie
          ignore:
            - venv/
            - data/fixtures/
        - action: rebuild
          path: Pipfile.lock
        - action: rebuild
          path: config.py
    restart: unless-stopped #no, always, on-failure: 5, unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
