FROM python:3.12-slim

RUN useradd --create-home userapi

WORKDIR /usr/src/flask_movie

RUN apt-get update && apt-get install -y netcat-openbsd

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN pip install --no-cache-dir pipenv

COPY Pipfile .
COPY Pipfile.lock .

RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy --system

COPY . .

RUN chown -R userapi:userapi /usr/src/flask_movie
USER userapi

EXPOSE 5000

CMD ["python", "wsgi.py"]
